spring.application.name=web

# Database Aiven Cloud cho local development
# Lưu ý: Cần whitelist IP của bạn trên Aiven Cloud
spring.datasource.url=jdbc:mysql://bapngo-ngovanquanghau-26.f.aivencloud.com:17203/web?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_qvpf3YTQqbLOQYiyW_n
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gdrive.service-account-key-path=classpath:todo-list-475513-a9f849b5d280.json
gdrive.parent-folder-id=0AFuDj2IFCqntUk9PVA
